// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhr6DmKVaUYTzs08gljBhxmZMEnEDbvQM',
    appId: '1:871403008139:web:ad943dd810e1267e42a48e',
    messagingSenderId: '871403008139',
    projectId: 'whatsapp-d843c',
    authDomain: 'whatsapp-d843c.firebaseapp.com',
    storageBucket: 'whatsapp-d843c.appspot.com',
    measurementId: 'G-HYNM9VEEBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_5UXxqFf7fTddyTyAg_Mx9O2DtOtAcyo',
    appId: '1:871403008139:android:503292d425b2440b42a48e',
    messagingSenderId: '871403008139',
    projectId: 'whatsapp-d843c',
    storageBucket: 'whatsapp-d843c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByWtHMRbcVkem3cZzZpI6ZaU_oW5H0ZPc',
    appId: '1:871403008139:ios:6d55504dcca7125b42a48e',
    messagingSenderId: '871403008139',
    projectId: 'whatsapp-d843c',
    storageBucket: 'whatsapp-d843c.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByWtHMRbcVkem3cZzZpI6ZaU_oW5H0ZPc',
    appId: '1:871403008139:ios:92a9a76cc8ead54642a48e',
    messagingSenderId: '871403008139',
    projectId: 'whatsapp-d843c',
    storageBucket: 'whatsapp-d843c.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
